name: CI/CD Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context_name: ./frontend
            image_name: ghcr.io/yasinenifa/cicd-projet2/frontend:latest
          - context_name: ./node-api
            image_name: ghcr.io/yasinenifa/cicd-projet2/node-api:latest
    permissions:
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ${{matrix.image_name}}

      - name: login To Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: ${{matrix.context_name}}
          push: true
          tags: ${{matrix.image_name}}
          cache-from: type=gha
          cache-to: type=gha, mode=max #Mettre en cache toutes les layers
