name: CI/CD Workflow
on: push
jobs:
  tests-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install Dependencies
        run: npm ci --prefer-offline
      - name: Linter
        run: npm run lint
      # - name: npm audit
      #   run: npm audit --audit-level=moderate

  tests-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node-api
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: ./node-api/package-lock.json
      - name: Install Dependencies
        run: npm ci --prefer-offline
      - name: Linter
        run: npm run lint
      # - name: npm audit
      #   run: npm audit --audit-level=moderate
      - name: Run unit tests
        run: npm run test:ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [tests-frontend, tests-backend]
    strategy:
      matrix:
        include:
          - context_name: ./frontend
            image_name: ghcr.io/yasinenifa/cicd-projet2/frontend:latest
          - context_name: ./node-api
            image_name: ghcr.io/yasinenifa/cicd-projet2/node-api:latest
    permissions:
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: ${{matrix.image_name}}

      - name: login To Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: ${{matrix.context_name}}
          push: true
          tags: ${{matrix.image_name}}
          cache-from: type=gha
          cache-to: type=gha, mode=max #Mettre en cache toutes les layers
